Models/ErrorViewModel.cs
namespace BuiHuuPhuc.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Controllers/HomeController.cs
using BuiHuuPhuc.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace BuiHuuPhuc.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/SinhVienController.cs
using Microsoft.AspNetCore.Mvc;
using Test.Models;
using Test.Repository;


namespace BuiHuuPhuc.Controllers
{
    public class SinhVienController : Controller
    {
        AllRepository<SinhVien> repo;
        HuhuContext context;
        public SinhVienController()
        {
            context = new HuhuContext();
            repo = new AllRepository<SinhVien>(context, context.SinhViens);
        }
        public IActionResult Index()
        {
            var a = repo.GetAll();
            return View(a);
        }
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(SinhVien singVien)
        {
            singVien.Id = Guid.NewGuid();
            repo.CreateObj(singVien);
            return RedirectToAction("Index");
        }
        public IActionResult Update(Guid id)
        {
            var singVien = repo.GetByID(id);
            return View(singVien);
        }
        [HttpPost]
        public IActionResult Update(SinhVien singVien)
        {
            repo.UpdateObj(singVien);
            return RedirectToAction("Index");
        }
        public IActionResult Delete(Guid id)
        {
            var singVien = repo.GetByID(id);
            repo.DeleteObj(singVien);
            return RedirectToAction("Index");
        }
        public IActionResult Details(Guid id)
        {
            var singVien = repo.GetByID(id);
            return View(singVien);
        }

    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BuiHuuPhuc</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/BuiHuuPhuc.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">BuiHuuPhuc</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="SinhVien" asp-action="Index">DanhSach</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - BuiHuuPhuc - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/SinhVien/Create.cshtml
@model Test.Models.SinhVien
@{
    ViewData["Title"] = "Create";

}

<h1>Create</h1>

<h4>SinhVien</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Id" class="control-label"></label>
                <input asp-for="Id" class="form-control" />
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Ten" class="control-label"></label>
                <input asp-for="Ten" class="form-control" />
                <span asp-validation-for="Ten" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Tuoi" class="control-label"></label>
                <input asp-for="Tuoi" class="form-control" />
                <span asp-validation-for="Tuoi" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Nganh" class="control-label"></label>
                <input asp-for="Nganh" class="form-control" />
                <span asp-validation-for="Nganh" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/SinhVien/Delete.cshtml
@model Test.Models.SinhVien

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>SinhVien</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Ten)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Ten)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Tuoi)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Tuoi)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nganh)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nganh)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/SinhVien/Details.cshtml
@model Test.Models.SinhVien

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>SinhVien</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Ten)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Ten)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Tuoi)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Tuoi)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nganh)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nganh)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    <a asp-action="Index">Back to List</a>
</div>

Views/SinhVien/Index.cshtml
@model IEnumerable<Test.Models.SinhVien>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Ten)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Tuoi)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Nganh)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Ten)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Tuoi)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Nganh)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
            </td>
        </tr>
}
    </tbody>
</table>

Views/SinhVien/Update.cshtml
@model Test.Models.SinhVien

@{
    ViewData["Title"] = "Update";
}

<h1>Update</h1>

<h4>SinhVien</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Update">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Id" class="control-label"></label>
                <input asp-for="Id" class="form-control" />
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Ten" class="control-label"></label>
                <input asp-for="Ten" class="form-control" />
                <span asp-validation-for="Ten" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Tuoi" class="control-label"></label>
                <input asp-for="Tuoi" class="form-control" />
                <span asp-validation-for="Tuoi" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Nganh" class="control-label"></label>
                <input asp-for="Nganh" class="form-control" />
                <span asp-validation-for="Nganh" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}